export enum ChooseTablesActionTypes {
    SHOW_CHOOSE_WINDOW = "SHOW_CHOOSE_WINDOW",
    HIDE_CHOOSE_WINDOW = "HIDE_CHOOSE_WINDOW",
    GET_TABLES = "GET_TABLES",
    CHANGE_ACTIVES = "CHANGE_ACTIVES",
}