export enum BusinessOperationLogsActionTypes {
    CHANGE_BUSINESS_OPERATION_LOGS_WINDOW_STATUS = "CHANGE_BUSINESS_OPERATION_LOGS_WINDOW_STATUS",
    GET_BUSINESS_OPERATION_LOGS = "GET_BUSINESS_OPERATION_LOGS"
}