export enum EditBusinessAdminActionTypes {
    SEARCH_USERS = "SEARCH_USERS",
    CHANGE_BUSINESS_ADMIN = "CHANGE_BUSINESS_ADMIN",
    CHANGE_SEARCH_STATUS = "CHANGE_SEARCH_STATUS",
    GET_BUSINESS_ADMIN = "GET_BUSINESS_ADMIN"
}