export enum CreateUserActionTypes {
    CHANGE_USER = "CHANGE_USER",
    SHOW_CREATE_USER_WINDOW = "SHOW_CREATE_USER_WINDOW",
    HIDE_CREATE_USER_WINDOW = "HIDE_CREATE_USER_WINDOW",
    CREATE_USER = "CREATE_USER",
    CHANGE_USERNAME = "CHANGE_USERNAME"
}