export enum FieldsActionTypes  {
    GET_FIELDS  = "GET_FIELDS",
    EDIT_FIELD_DESCRIPTION = "EDIT_FIELD_DESCRIPT",
    EDIT_FIELD_DICT = "EDIT_FIELD_DICT",
    SET_FIELD_NAME_COLUMN_WIDTH = "SET_FIELD_NAME_COLUMN_WIDTH",
    CHANGE_LOCK_STARUS = "CHANGE_FIELD_LOCK_STARUS"
}