export enum CreateBusinessActives {
    CHANGE_ACTIVES = "CREATE_BUSINESS_CHANGE_ACTIVES",
    SHOW_CREATE_BUSINESS_WINDOW = "SHOW_CREATE_BUSINESS_WINDOW",
    HIDE_CREATE_BUSINESS_WINDOW = "HIDE_CREATE_BUSINESS_WINDOW",
    CREATE_BUSINESS = "CREATE_BUSINESS"
}