export enum SecretActionTypes {
    GET_SECRET_TABLES = "GET_SECRET_TABLES",
    SET_TABLE_NAME_WIDTH = "SET_TABLE_NAME_WIDTH",
    UN_LOCK_TABLE = "SECRET_UN_LOCK_TABLE",
    LOCK_TABLES = "SECRET_LOCK_TABLES"
}