export enum LineageActionTypes {
    GET_TABLE_LINEAGE = "GET_TABLE_LINEAGE",
    ADD_TABLE_LINEAGE = "ADD_TABLE_LINEAGE",
    CHNAGE_UNWATCH_TABLES = "CHNAGE_UNWATCH_TABLES",
    SHOW_TABLE_INFO = "SHOW_TABLE_INFO",
    HIDE_TABLE_INFO = "HIDE_TABLE_INFO",
    CHANGE_VIEW_MODL = "CHANGE_VIEW_MODL"
}