export enum EditAuthorizeActionTypes {
    HIDE_EDIT_AUTHORIZE = "HIDE_EDIT_AUTHORIZE",
    SHOW_EDIT_AUTHORIZE = "SHOW_EDIT_AUTHORIZE",
    GET_USER_AUTHORIZE = "GET_USER_AUTHORIZE",
    GET_ALL_SECRET_TABLES = "GET_ALL_SECRET_TABLES",
    CHANGE_ACTIVES = "EDIT_AUTHOPRIZE_CHANGE_ACTIVES",
    EDIT_AUTHORIZE = "EDIT_AUTHORIZE"
}