export enum CreateTemplateActionTypes {
    SUBMIT_TEMPLATE = "SUBMIT_TEMPLATE",
    UPDATE_TEMPLATE = "UPDATE_TEMPLATE",
    SHOW_CREATE_TEMPLATE = "SHOW_CREATE_TEMPLATE",
    HIDE_CREATE_TEMPLATE = "HIDE_CREATE_TEMPLATE",
    CHANGE_VALIDATE_STATUS = "CHANGE_VALIDATE_STATUS"
}