export enum EditBusinessActionTypes {
    CHANGE_ACTIVES = "EDIT_BUSINESS_CHANGE_ACTIVES",
    SHOW_Edit_BUSINESS_WINDOW = "SHOW_EDIT_BUSINESS_WINDOW",
    HIDE_EDIT_BUSINESS_WINDOW = "HIDE_EDIT_BUSINESS_WINDOW",
    EDIT_BUSINESS = "EDIT_BUSINESS",
}