export enum FieldNullvalueMonitorActionTypes {
    GET_FIELD_NULLVALUES = "GET_FIELD_NULLVALUES",
    GET_FIELD_INFOS = "GET_FIELD_INFOS_FOR_NULLVALUE",
    CHANGE_CURRENT_FIELD = "CHANGE_CURRENT_FIELD"
}