export enum OperationLogsAuthorizeActionTypes {
    CHNAGE_ACTIVES = "CHNAGE_ACTIVES",
    GET_USERS = "GET_USERS",
    SUBMIT_AUTHORIZE = "SUBMIT_AUTHORIZE",
    GET_OPERATION_LOGS_AUTHORIZE = "GET_OPERATION_LOGS_AUTHORIZE"
}