export enum EditTypeActionTypes {
    SHOW_EDIT_TABLE_WINDOW = "SHOW_EDIT_TABLE_WINDOW",
    HIDE_EDIT_TABLE_WINDOW = "HIDE_EDIT_TABLE_WINDOW",
    EDIT_TABLE = "EDIT_TABLE",
    GET_ALL_TEMPLATES = "GET_ALL_TEMPLATES",
    GET_BUSINESS_FOR_ADMIN = "GET_BUSINESS_FOR_ADMIN"
}