export enum TablesActionTypes {
    GET_BUSSIONESS_INFO = "GET_BUSSIONESS_INFO",
    LOCK_TABLE = "LOCK_TABLE",
    UN_LOCK_TABLE = "UN_LOCK_TABLE",
    EDIT_TABLE_DESCRIPTION = "TABLES_EDIT_TABLE_DESCRIPT",
    SET_TABLE_NAME_COLUMN_WIDTH = "SET_TABLE_NAME_COLUMN_WIDTH",
    GET_BUSINESS_FOR_ADMIN = "GET_BUSINESS_FOR_ADMIN_TABLES",
    EDOIT_TABLE_BUSINESS = "EDOIT_TABLE_BUSINESS"
}